# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end





=begin

Code BEFORE Part 2: Step 7

# db/seeds.rb
# Loads the "csv" library to read the CSV file
require 'csv'

# Loads the "faker" gem/package, which is used to generate fake data for the products.
require 'faker'

# Clearing existing products. This is to avoid duplications.
Product.destroy_all

# The "times" method iterates the block of code 676 times.
676.times do
  # Creating a new product record in the database. The "create" method instantiates a new product object and saves it to the database in a single step.
  Product.create(
    # Sets the "title" attribute of the product to a randomly generated product name using the "Faker::Commerce.product_name" method.
    title: Faker::Commerce.product_name,
    # sets the "description" attribute of the product to a randomly generated paragraph using the "Faker::Lorem.paragraph" method.
    description: Faker::Lorem.paragraph,
    # Sets the "price" attribute of the product to a randomly generated price between 0.0 and 500.0 using the "Faker::Commerce.price" method with the specified range.
    price: Faker::Commerce.price(range: 0.0..500.0),
    # Sets the "stock_quantity" attribute of the product to a randomly generated number between 1 and 500 using the "Faker::Number.between" method.
    stock_quantity: Faker::Number.between(from: 1, to: 500)
  )
end

# Printing a message to the console indicating that 676 products have been created.
puts "Created 676 products with random data that was generated by the faker gem."
=end





# Code AFTER Part 2: Step 7

# db/seeds.rb
# Loads the "csv" library to read the CSV file
require 'csv'

# Clearing existing products and categories. This is to avoid duplications.
Product.destroy_all
Category.destroy_all

# Read the CSV file
csv_file = Rails.root.join('db', 'products.csv')
csv_data = File.read(csv_file)

# Parse the CSV data
products = CSV.parse(csv_data, headers: true)

# If CSV was created by Excel in Windows you may also need to set an encoding type:
# products = CSV.parse(csv_data, headers: true, encoding: 'iso-8859-1')

# Loop through each row in the CSV file
products.each do |product|
  # Get the category name from the CSV data
  category_name = product['category']

  # Find or create the category by name
  category = Category.find_or_create_by(name: category_name)

  # Create the product and associate it with the category
  Product.create!(
    title: product['name'],
    price: product['price'],
    description: product['description'],
    stock_quantity: product['stock quantity'],
    category: category
  )
end

# Printing a message to the console indicating that "products" from the CSV file have been created.
puts "Products imported from CSV file."
